import type { Metadata } from 'next';
import { Poppins, Pacifico } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  display: 'swap',
});

const pacifico = Pacifico({
  variable: '--font-pacificio',
  display: 'swap',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/Logo.png" />
      <body
        className={`${poppins.variable} ${pacifico.variable} overflow-x-hidden antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
